version: "3.9"

volumes:
  data:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3111
    ports:
      - 3111:8000
      - "8443:8000"
    restart: unless-stopped
    volumes:
      - data:/app/data